---
abstract: 'Add plugin support for the Perl debugger'
author:
  - 'Keith Carangelo <mail@kcaran.com>'
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: '0'
  File::Find: '0'
  File::Temp: '0'
  Scalar::Util: '0'
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DB-Pluggable
recommends:
  Brickyard: '1.111750'
  Parallel::ForkManager: v0.7.6
requires:
  Brickyard: '1.111750'
  Brickyard::Accessor: '0'
  Brickyard::Role::Plugin: '0'
  Data::Printer: '0'
  Hook::LexWrap: '0'
  Role::Basic: '0'
  Test::Builder: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kcaran/DB-Pluggable/issues
  homepage: https://github.com/kcaran/DB-Pluggable
  repository: https://github.com/kcaran/DB-Pluggable.git
version: '1.12'
x_generated_by_perl: v5.26.3
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
